2023-10-11 13:48:54,834 INFO    StreamThr :17004 [internal.py:wandb_internal():86] W&B internal server running at pid: 17004, started at: 2023-10-11 13:48:54.834032
2023-10-11 13:48:54,835 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: status
2023-10-11 13:48:54,839 INFO    WriterThread:17004 [datastore.py:open_for_write():85] open: D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\data_process\wandb\run-20231011_134854-5ko3l8gm\run-5ko3l8gm.wandb
2023-10-11 13:48:54,839 DEBUG   SenderThread:17004 [sender.py:send():375] send: header
2023-10-11 13:48:54,954 DEBUG   SenderThread:17004 [sender.py:send():375] send: run
2023-10-11 13:48:58,416 INFO    SenderThread:17004 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Software\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Software\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Software\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
2023-10-11 13:48:59,991 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:05,035 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:10,064 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:15,103 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:20,151 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:25,186 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:30,207 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:35,230 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:40,263 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:45,299 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:50,324 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: keepalive
2023-10-11 13:49:55,365 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: cancel
2023-10-11 13:49:55,365 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: cancel
2023-10-11 13:49:55,365 DEBUG   SenderThread:17004 [sender.py:send():384] Record cancelled: run
2023-10-11 13:49:55,366 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: status_report
2023-10-11 13:49:55,431 DEBUG   HandlerThread:17004 [handler.py:handle_request():144] handle_request: shutdown
2023-10-11 13:49:55,432 INFO    HandlerThread:17004 [handler.py:finish():845] shutting down handler
2023-10-11 13:49:56,370 INFO    SenderThread:17004 [sender.py:finish():1550] shutting down sender
2023-10-11 13:49:56,370 INFO    WriterThread:17004 [datastore.py:close():298] close: D:\Study\Emotive\BrainLinkNetwork\FAT-WAKE\data_process\wandb\run-20231011_134854-5ko3l8gm\run-5ko3l8gm.wandb
